package routes

import (
	"cv-analyzer/internal/application/usecases"
	"cv-analyzer/internal/interfaces/api/handlers"
	"github.com/gin-gonic/gin"
	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"
	// _ "cv-analyzer/api/docs" // docs is generated by Swag CLI - MOVING TO MAIN.GO
)

// SetupRouter configures the Gin router with all application routes.
// Now accepts AnalysisHandler as a dependency.
func SetupRouter(analysisHandler *handlers.AnalysisHandler) *gin.Engine {
	router := gin.Default()

	// Swagger documentation endpoint
	// The URL for Swagger UI will be /swagger/index.html
	// Explicitly set the URL for swagger.json
	router.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler, ginSwagger.URL("/swagger/doc.json")))

	// Group API routes
	apiGroup := router.Group("/api/v1")
	{
		// Analysis routes
		analysisRoutes := apiGroup.Group("/analysis")
		{
			// POST /api/v1/analysis/cv
			// Renamed from /analyze to be more RESTful and fit within the /analysis group
			analysisRoutes.POST("/cv", analysisHandler.HandleAnalyzeCV) // Corrected method name
			// Future enhancement: Could add GET routes to retrieve specific analysis results
			// e.g., analysisRoutes.GET("/:id", analysisHandler.GetAnalysisResult)
		}

		// TODO: Add routes for CV management (upload, get, list, delete)
		// cvRoutes := apiGroup.Group("/cvs")
		// {
		// 	cvRoutes.POST("/", cvHandler.UploadCV)
		// 	cvRoutes.GET("/:id", cvHandler.GetCV)
		// }

		// TODO: Add routes for JD management
		// jdRoutes := apiGroup.Group("/jds")
		// {
		//  jdRoutes.POST("/", jdHandler.UploadJD)
		//	jdRoutes.GET("/:id", jdHandler.GetJD)
		// }
	}

	// Basic health check route
	router.GET("/health", func(c *gin.Context) {
		c.JSON(200, gin.H{
			"status": "UP",
		})
	})

	return router
}
