package main

import (
	// "cv-analyzer/internal/application/usecases" // Temporarily commented for wire
	// "cv-analyzer/internal/infrastructure/filesystem" // Temporarily commented for wire
	// "cv-analyzer/internal/infrastructure/llm" // Temporarily commented for wire
	// "cv-analyzer/internal/application/usecases" // No longer needed directly if main calls initializeAPI
	// "cv-analyzer/internal/infrastructure/filesystem" // No longer needed directly
	// "cv-analyzer/internal/infrastructure/llm" // No longer needed directly
	// "cv-analyzer/internal/infrastructure/persistence" // No longer needed directly
	// "cv-analyzer/internal/interfaces/api/routes" // No longer needed directly
	"fmt"
	"log" // Re-enable log for fatal errors
	// "net/http" // Import if you need to customize the http.Server

	_ "cv-analyzer/api/docs" // docs is generated by Swag CLI
)

// @title CV Analyzer API
// @version 1.0
// @description This is a server for analyzing CVs against Job Descriptions.
// @termsOfService http://swagger.io/terms/

// @contact.name API Support
// @contact.url http://www.swagger.io/support
// @contact.email support@swagger.io

// @license.name Apache 2.0
// @license.url http://www.apache.org/licenses/LICENSE-2.0.html

// @host localhost:8080
// @BasePath /api/v1
// @schemes http https
func main() {
	fmt.Println("Starting CV Analyzer API...")

	// Initialize services
	// Instead of individual dummy parsers, we'll use the ParserRouter.
	// The main function will be simplified to use the Wire-generated injector.
	// Manual DI graph construction is removed from here.

	fmt.Println("Starting CV Analyzer API with Wire...")

	// Call the Wire injector (once wire_gen.go is generated)
	// For now, this main function is a placeholder to allow `wire` to generate.
	// After `wire gen` run, it should be:
	/*
	ginEngine, err := initializeAPI()
	if err != nil {
		log.Fatalf("Failed to initialize API: %v", err)
	}

	serverAddr := ":8080"
	fmt.Printf("Server listening on %s\n", serverAddr)
	if err := ginEngine.Run(serverAddr); err != nil {
		log.Fatalf("Failed to run server: %v", err)
	}
	*/

	// Placeholder to allow `go build` to pass before wire_gen.go exists.
	// This part will be replaced after successful `wire` generation.
	// fmt.Println("Wire injector to be called here. Run 'wire ./cmd/cv-analyzer' to generate.")
	// fmt.Println("Then update main() to use initializeAPI().")

	ginEngine, err := initializeAPI()
	if err != nil {
		log.Fatalf("Failed to initialize API: %v", err)
	}

	serverAddr := ":8080"
	fmt.Printf("Server listening on %s (initialized with Wire)\n", serverAddr)
	if err := ginEngine.Run(serverAddr); err != nil {
		log.Fatalf("Failed to run server: %v", err)
	}
}
