// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"cv-analyzer/internal/application/ports"
	"cv-analyzer/internal/application/usecases"
	"cv-analyzer/internal/infrastructure/filesystem"
	"cv-analyzer/internal/infrastructure/llm"
	"cv-analyzer/internal/infrastructure/persistence"
	"cv-analyzer/internal/interfaces/api/handlers"
	"cv-analyzer/internal/interfaces/api/routes"
	"fmt"
	"github.com/gin-gonic/gin"
	"os"
)

import (
	_ "cv-analyzer/api/docs"
)

// Injectors from wire.go:

// --- Main Injector ---
// initializeAPI is the main injector function that Wire will implement.
func initializeAPI() (*gin.Engine, error) {
	plainTextParser := filesystem.NewPlainTextParser()
	pdfParser := filesystem.NewPdfParser()
	parserRouter, err := filesystem.NewParserRouter(plainTextParser, pdfParser)
	if err != nil {
		return nil, err
	}
	analysisService := provideDummyAnalysisService()
	inMemoryStorage, err := persistence.NewInMemoryStorage()
	if err != nil {
		return nil, err
	}
	analyzeCVUseCase := provideAnalyzeCVUseCase(parserRouter, analysisService, inMemoryStorage)
	analysisHandler := provideAnalysisHandler(analyzeCVUseCase)
	engine := provideGinEngine(analysisHandler)
	return engine, nil
}

// wire.go:

// Provider for LLM Analysis Service
// Option 1: Dummy service
func provideDummyAnalysisService() ports.AnalysisService {

	apiKey := os.Getenv("OPENAI_API_KEY")

	oa, err := llm.NewOpenAIAdapter(apiKey)
	if err != nil {

		panic(fmt.Sprintf("Failed to init OpenAIAdapter: %v. Make sure OPENAI_API_KEY is set if intending to use it, or configure a fallback dummy service.", err))
	}
	return oa
}

func provideAnalyzeCVUseCase(
	parserRouter ports.FileParserRouter,
	analysisService ports.AnalysisService,
	storageService ports.StorageService,
) *usecases.AnalyzeCVUseCase {
	return usecases.NewAnalyzeCVUseCase(parserRouter, analysisService, storageService)
}

func provideAnalysisHandler(useCase *usecases.AnalyzeCVUseCase) *handlers.AnalysisHandler {
	return handlers.NewAnalysisHandler(*useCase)
}

// provideGinEngine initializes the Gin engine and sets up routes.
// Now depends on AnalysisHandler, which is provided by Wire.
func provideGinEngine(analysisHandler *handlers.AnalysisHandler) *gin.Engine {

	return routes.SetupRouter(analysisHandler)
}
